apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-name
  namespace: ns
spec:
  selector:
    matchLabels:
      app: label
  template:
    metadata:
      labels:
        app: label
    spec:
      containers:
      - name: label
        image: imageName:buildid
        ports:
        - containerPort: cport
      imagePullSecrets:
        -  name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: svc-name
  namespace: ns
spec:
  selector:
    app: label
  ports:
  - port:  out-port
    targetPort: cport
