apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-django
  template:
    metadata:
      labels:
        app: blog-django
    spec:
      containers:
      - name: blog-django-container
        image: yegekucuk.azurecr.io/dev/blog-django:buildid
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/src/app/db
          name: blog-django-storage
          readOnly: false
      imagePullSecrets:
      - name: acr-pull-secret
      volumes:
      - name: blog-django-storage
        persistentVolumeClaim:
          claimName: blog-django-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: blog-django-service
spec:
  type: LoadBalancer
  selector:
    app: blog-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: blog-django-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
